version: '2.15.1'

services:
    postman:
        container_name: exchangeAPITest
        build:
            context: ./
            dockerfile: dockerfile.yml
        image: exchange_api_test
        command:
            run postman_collection.json
        volumes:
            - ./:/etc/newman

